In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re

from konlpy.tag import Okt

In [3]:
df1 = pd.read_csv('고민상담.csv', encoding ='utf-8')
df2 = pd.read_csv('공황장애고민.csv', encoding ='utf-8')
df3 = pd.read_csv('군입대고민.csv', encoding ='utf-8')
df4 = pd.read_csv('다이어트고민.csv', encoding ='utf-8')
df5 = pd.read_csv('대학생활고민.csv', encoding ='utf-8')
df6 = pd.read_csv('몸매고민.csv', encoding ='utf-8')
df7 = pd.read_csv('부부고민.csv', encoding ='utf-8')
df8 = pd.read_csv('불안장애고민.csv', encoding ='utf-8')
df9 = pd.read_csv('사랑고민.csv', encoding ='utf-8')
df10 = pd.read_csv('심리상담.csv', encoding ='utf-8')
df11 = pd.read_csv('연상고민.csv', encoding ='utf-8')
df12 = pd.read_csv('연애고민.csv', encoding ='utf-8')
df13 = pd.read_csv('연인관계고민.csv', encoding ='utf-8')
df14 = pd.read_csv('연하고민.csv', encoding ='utf-8')
df15 = pd.read_csv('외모고민.csv', encoding ='utf-8')
df16 = pd.read_csv('우울증고민.csv', encoding ='utf-8')
df17 = pd.read_csv('이별고민.csv', encoding ='utf-8')
df18 = pd.read_csv('이혼고민.csv', encoding ='utf-8')
df19 = pd.read_csv('입시고민.csv', encoding ='utf-8')
df20 = pd.read_csv('직장고민.csv', encoding ='utf-8')
df21 = pd.read_csv('직장생활고민.csv', encoding ='utf-8')
df22 = pd.read_csv('진로고민.csv', encoding ='utf-8')
df23 = pd.read_csv('취업고민.csv', encoding ='utf-8')
df24 = pd.read_csv('친구관계고민.csv', encoding ='utf-8')
df25 = pd.read_csv('퇴사고민.csv', encoding ='utf-8')
df26 = pd.read_csv('피부고민.csv', encoding ='utf-8')
df27 = pd.read_csv('학업고민.csv', encoding ='utf-8')

In [4]:
df1

Unnamed: 0  index                                               text
0             0      0                          저 직업고민상담쫌 해주세요ㅜㅜㅜㅜㅜ제발>>>>
1             1      1  실시간으로 고민 상담해주는 사이트좀 알려줘요>>> > >실시간으로 고민 상담해주는 ...
2             2      2  고민상담전화 개인정보>>> >고민상담 전화 하려는데요>친구 관계거든요 애들이랑 싸워...
3             4      4  입시생고민 상담>>> >안녕하세요 고 남학생인데요 이러는 시간이 없는거 알지만 들어...
4             5      5  고민상담은 삼촌>>>            >>>>         >>>>>     ...
5             6      6  고민 상담할 만한 곳>>> >저는 살 학생입니다 오늘따라 더 우울하고 슬프고 외로워...
6             7      7  고민상담좀 해주세요>>현재 공장 다니면서 하루 시간씩 일하고 교대 근무하면서 한달에...
7             8      8  진로진학 고민상담>이제 고됐는데요 동아리며 봉사활동이며 다 진로와 연결돼야 유리하다...
8             9      9  학과 고민 상담>>> >저는 살 이고 현재 년제 대학교에서 호텔관광계열을 공부 하고...
9            10     10  고민상담사이트>>> >>고민상담사이트 중에 친구한테 들었는데 빅 시스터즈 라는게 있...
10           11     11  고민 상담>>> >안녕하세요 학년 여고생인데요 제가 결정한 길에 대해서 고민이 많아...
11           12     12  고민상담이요>저는 친구들과 잘 지내고 있는 평범한 중이에요 근데 제가 같이 다니는 ...
12           13     13  고민상담 해 주세요 >>안녕하세요 저는 동생 둘이 있는 초  학생입니다 >둘째는 여...
13           14     14  고 고민상담이요 급합니다>>> >고등학생 고민 상담이요 제발 저 좀 도와주세요 급합...
14           15     15  고민상담>>> >제가 친구명이 약간 사이가 나빠져서 이럴때 고민상담을 누구한테받을지...
15           16     16  친구 고민상담>>> >친구들이 고민상담을 해올때 뭐라고 생각하고 답해줘야할까요 그친...
16           17     17  고민상담 해주세요>>> >>>자퇴경험 잇으시거나 인간관계  아무나 고민상담 진지하게...
17           18     18  친구관계 고민 상담>>> >일단 저는 고여학생이고 제 친구도 고이에요초등학생때부터 ...
18           19     19  연애 고민상담좀>>> >안녕하세요 고 여학생입니다>제가 남친이랑 사귄지 일이 되었어...
19           20     20  코성형 고민상담의사분만 남겨주세요>현재 코성형한지는 개월밖에 안되었는데요>특별히 염...
20           21     21  심리고민상담 성향 성격 태도 등때문에 동생이 진짜 싫습니다>동생과 저는 둘다 대입니...
21           22     22  고민상담 부탁드려요ㅠㅠ 저는 지금 고등학교를 졸업했고 남자친구는 고입니다 저랑 친한...
22           23     23  고민상담 좀 해주세요ㅠ>학교폭력땜시 힘들어여ㅠ 원래 우리반 저와 같은 성별인 애들끼...
23           24     24  고등학교 자퇴 고민 상담>안녕하세요 현재 학교에서 자퇴를 고민중인 학생입니다>자퇴 ...
24           25     25  여러분들 제 고민상담 좀 해주세요>전 중  여자아이구요 고등학교 진학을 앞뒀습니다 ...
25           27     27  친구 고민 상담 문제입니다>>> >저랑 제일 친한 친구가 있습니다>그 친구랑 저는 ...
26           28     28  고졸  대학 졸업장 고민 상담 부탁드립니다내공 >>> >>전문대 다니고 있는 살 남...
27           29     29    여잔데요 연애고민 상담할때 여자한테 하는게 낫나요 아님 남자한테 하는게 낫나요>>>>
28           30     30  고민상담 잘하는법좀 알려주세요ㅜㅜ>>> >안녕하세요 올해 고되는 남학생입니다 >제가...
29           31     31  고민상담입니다>제가 학교에서 짝사랑하는 귀여운 남자애가 있어요>근데 제 단짝친구 비...
..          ...    ...                                                ...
889         966    966  고민상담좀요>>> >>저는 제주사는 살 입니다 저는 코에 점이 있어요 근데 그게 콤...
890         967    967  진로 고민 상담좀요>>> >>살 대학생입니다>>이번에 반 학기 휴학하면서제 인생에 ...
891         968    968  고등학교 자퇴 고민 상담>>> >저는 학교폭력 피해자입니다 시작은 중 연말부터 시작...
892         971    971  진로고민 상담쪽>>> >>>>>안녕하세요>>>>>사회초년생이예요>>>>>현재 살 여...
893         972    972  고민상담>안녕하세요 년생 여학생입니다>제가 고민이 좀 많은데 몇가지좀 끄적끄적할려고...
894         973    973  중여잔데요정말 딱히 고민상담 할곳이 없어서 글 올려봅니다>이제 고교 진학을 앞두고 ...
895         975    975  고민상담좀 해주세요>>> >안녕하세요 중 여자 입니다>진짜진짜 년전으로 돌아가고 싶...
896         976    976  고민상담좀 해주십쇼>>> >제가 년동안 좋아했고 지금도 좋아하는중인 여자애가 있는데...
897         977    977                                       고민상담해주실분>>>>
898         978    978  고민 상담할 만한 곳>>> >저는 살 학생입니다 오늘따라 더 우울하고 슬프고 외로워...
899         979    979  고민상담을 하고 싶습니다 중여자구요>톡이든 전화든 만남이든 상관 없어요>조언을 안해...
900         980    980  고민상담좀 해주세요>>현재 공장 다니면서 하루 시간씩 일하고 교대 근무하면서 한달에...
901         981    981  학교폭력 고민 상담>>> >저희 특성화고가 하도 시골 똥통 학교라서 교사나 학생들이...
902         982    982  중학교 학년 고민상담>>> >>안녕하세요 저는 현재 중학교 학년인 한 학생입니다 지...
903         983    983  고민상담해주세요>>> >진짜 진지하게 제 고민상담 해주실분 구해요 ㅠ>대 얼굴보고 ...
904         984    984  고민 상담 해주세요>>> >저희 부모님은 제가 말도하지 못할정도로 어릴때 이혼하셨어...
905         985    985  비올리 가격 싼곳 및 고민상담>>> >>가슴확대로 좋다는 비올리 가격 좀 알아보는데...
906         987    987  고학생 유학고민상담좀 해주세요ㅠㅠ >지금고이고 일반고 재학중이에요 성적은 등급정도 ...
907         988    988  고민상담 >>왜자꾸 옛날 고구려나고려 이런시대때를생각하면왜자꾸아련하죠가슴이먹먹해요 ...
908         989    989  탈모 아닌가요고민상담>>> >고등학생입니다>전 머리가 많이 빠지는 것 같아요>이렇게...
909         990    990  고민 상담 해주세요>>> >안녕하세요>바로 본론 들어가겠습니다 >현재 중인 여학생입...
910         991    991  안녕하세요 제가 친구문제로 고민상담을좀 하려고 합니다제가 중 여자인데 학년때부터 친...
911      

In [5]:
def test(s):
    hangul = re.compile('[^ ㄱ-ㅣ가-힣]+') # 한글과 띄어쓰기를 제외한 모든 글자
    result = hangul.sub('', s) # 한글과 띄어쓰기를 제외한 모든 부분을 제거
    return result

In [6]:
def make_label(df):
    df= df.drop(['Unnamed: 0','index'], axis =1)
    df.columns = ['text']
    df['label'] = 0
    for i in range(len(df['text'])):
        if df['text'][i] == '\n':
            df['label'][i-1] = 1
            df = df.drop([i])
            
    df['text'] = df['text'].apply(lambda x : test(x))

    return df

In [7]:
df1 = make_label(df1)
df2 = make_label(df2)
df3 = make_label(df3)
df4 = make_label(df4)
df5 = make_label(df5)
df6 = make_label(df6)
df7 = make_label(df7)
df8 = make_label(df8)
df9 = make_label(df9)
df10 = make_label(df10)
df11 = make_label(df11)
df12 = make_label(df12)
df13 = make_label(df13)
df14 = make_label(df14)
df15 = make_label(df15)
df16 = make_label(df16)
df17 = make_label(df17)
df18 = make_label(df18)
df19 = make_label(df19)
df20 = make_label(df20)
df21 = make_label(df21)
df22 = make_label(df22)
df23 = make_label(df23)
df24 = make_label(df24)
df25 = make_label(df25)
df26 = make_label(df26)
df27 = make_label(df27)


In [8]:
df1.label = 1
df2.label = 2
df3.label = 3
df4.label = 4
df5.label = 5
df6.label = 6
df7.label = 7
df8.label = 8
df9.label = 9
df10.label = 10
df11.label = 11
df12.label = 12
df13.label = 13
df14.label = 14
df15.label = 15
df16.label = 16
df17.label = 17
df18.label = 18
df19.label = 19
df20.label = 20
df21.label = 21
df22.label = 22
df23.label = 23
df24.label = 24
df25.label = 25
df26.label = 26
df27.label = 27

In [9]:
f_df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,\
          df21,df22,df23,df24,df25,df26,df27], axis=0)

In [10]:
f_df.index = list(range(len(f_df)))

In [11]:
from tqdm import tqdm_notebook
from konlpy.tag import Okt

RE_FILTER = re.compile("[.,!?\"':;~()]")

def pos_tag(sentences):
    from tqdm import tqdm_notebook
    # KoNLPy 형태소분석기 설정
    tagger = Okt()
    
    # 문장 품사 변수 초기화
    sentences_pos = []
    
    # 모든 문장 반복
    for sentence in tqdm_notebook(sentences):
        # 특수기호 제거
        sentence = re.sub(RE_FILTER, "", sentence)
        
        # 배열인 형태소분석의 출력을 띄어쓰기로 구분하여 붙임
        sentence = " ".join(tagger.morphs(sentence))
        sentences_pos.append(sentence)
        
    return sentences_pos

In [ ]:
data= pos_tag(f_df.text)

C:\Users\user\Anaconda3\lib\site-packages\jpype\_core.py:210: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)


In [ ]:
df = pd.DataFrame(data)
df.columns= ['text']
df['label']= f_df.label

In [27]:
df.to_csv('고민분류용df.csv', encoding= 'utf-8')

In [34]:
data = []
df.text.apply(lambda x: data.append(x))

0        None
1        None
2        None
3        None
4        None
         ... 
24637    None
24638    None
24639    None
24640    None
24641    None
Name: text, Length: 24642, dtype: object

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf = TfidfVectorizer(max_features= 3000)

In [40]:
tfidf.fit(data)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=3000,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [48]:
data = tfidf.transform(data).toarray()

In [50]:
data.shape

(24642, 3000)

In [133]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data, df['label'], test_size = 0.2, random_state = 77)

In [134]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [135]:
x_train.shape

(19713, 3000)

In [136]:
y_train.shape

(19713, 28)

In [137]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(512, activation ='relu', input_shape=(3000,)))
model.add(layers.Dense(256, activation= 'relu'))
model.add(layers.Dense(256, activation= 'relu'))
model.add(layers.Dense(64, activation= 'relu'))
model.add(layers.Dense(28, activation='softmax'))

In [138]:
model.compile(optimizer='adam',\
              loss='categorical_crossentropy',\
              metrics=['accuracy'])

In [139]:
history = model.fit(x_train, y_train,\
                    epochs=5, batch_size = 128,validation_split=0.2)

Train on 15770 samples, validate on 3943 samples
Epoch 1/5
15770/15770 [==============================] - ETA: 1:04 - loss: 3.3307 - acc: 0.031 - ETA: 23s - loss: 3.3292 - acc: 0.062 - ETA: 15s - loss: 3.3267 - acc: 0.06 - ETA: 12s - loss: 3.3249 - acc: 0.06 - ETA: 11s - loss: 3.3225 - acc: 0.06 - ETA: 10s - loss: 3.3203 - acc: 0.06 - ETA: 9s - loss: 3.3158 - acc: 0.0668 - ETA: 8s - loss: 3.3075 - acc: 0.066 - ETA: 7s - loss: 3.2971 - acc: 0.067 - ETA: 7s - loss: 3.2877 - acc: 0.063 - ETA: 6s - loss: 3.2722 - acc: 0.070 - ETA: 6s - loss: 3.2519 - acc: 0.089 - ETA: 6s - loss: 3.2388 - acc: 0.099 - ETA: 5s - loss: 3.2127 - acc: 0.113 - ETA: 5s - loss: 3.1880 - acc: 0.125 - ETA: 5s - loss: 3.1540 - acc: 0.144 - ETA: 5s - loss: 3.1129 - acc: 0.161 - ETA: 4s - loss: 3.0681 - acc: 0.181 - ETA: 4s - loss: 3.0260 - acc: 0.195 - ETA: 4s - loss: 2.9858 - acc: 0.207 - ETA: 4s - loss: 2.9306 - acc: 0.225 - ETA: 4s - loss: 2.8797 - acc: 0.239 - ETA: 3s - loss: 2.8253 - acc: 0.255 - ETA: 3s - loss: 

In [140]:
model.evaluate(x_test,y_test)

4929/4929 [==============================] - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - ETA:  - 1s 106us/step


[0.63008880165388, 0.847839318320146]

In [145]:
sentence ='와이프가 저 몰래 연애를 합니다 '
test_sen = tfidf.transform([sentence]).toarray()
test_sen

array([[0., 0., 0., ..., 0., 0., 0.]])

In [146]:
model.predict_classes(test_sen)

array([1], dtype=int64)

In [88]:
sentence ='요새 뱃살이 너무나 쪄서 문제에요'

test_sen = tfidf.transform([sentence]).toarray()
model.predict_classes(test_sen)

array([3], dtype=int64)

In [89]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [92]:
x_train.shape

(19713, 3000)

In [97]:
clf.fit(x_train, y_train)

KeyboardInterrupt: 

In [103]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)


In [111]:
forest.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [108]:
y_train= y_train.values

In [110]:
y_train.shape

(19713,)

In [112]:
y_pred = forest.predict(x_test)

In [114]:
from sklearn import metrics 

In [115]:
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

정확도 : 0.8920673564617569


In [130]:
sentence ='요새 취업걱정 때문에 고민이에요'

test_sen = tfidf.transform([sentence]).toarray()

In [131]:
forest.predict(test_sen)

array([21], dtype=int64)