### 빅데이터 활용 AI 설계
# 신경망 구조

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### 사례 1
- 입력층 : 뉴런 2개
- 출력층 : 뉴런 1개
- 중간층 1개 : 뉴런 16개
- 중간층 활성화함수 : ReLU
- 손실값 : MSE

In [2]:
X = np.arange(10).reshape(5,2)
y = np.array([1,2,3,4,5])

In [5]:
W1 = np.random.normal(0,0.1,size=[2,16])
W1

array([[-0.22340921, -0.0494195 , -0.01219548, -0.01406233, -0.01670224,
         0.10556695, -0.20967331, -0.02389921,  0.0170729 ,  0.27497324,
        -0.0860843 , -0.1000081 ,  0.01727834, -0.13994928,  0.16243088,
         0.06380968],
       [ 0.01496708, -0.12783827, -0.03437618, -0.04147759,  0.12077003,
        -0.09992122,  0.04346617,  0.07703184,  0.02098992, -0.12177554,
        -0.02073986,  0.07935159,  0.03321312, -0.07734484, -0.03768014,
         0.04751735]])

In [6]:
W2 = np.random.normal(0,0.1,size=[16,1])
W2

array([[-0.02125226],
       [ 0.06353152],
       [-0.25604302],
       [-0.14153991],
       [ 0.1866319 ],
       [ 0.00287981],
       [-0.0858135 ],
       [ 0.04149463],
       [ 0.08219676],
       [ 0.0679731 ],
       [ 0.06420429],
       [ 0.04989921],
       [ 0.17673965],
       [ 0.03772194],
       [-0.09922862],
       [-0.00347503]])

In [7]:
h = X @ W1
h

array([[ 0.01496708, -0.12783827, -0.03437618, -0.04147759,  0.12077003,
        -0.09992122,  0.04346617,  0.07703184,  0.02098992, -0.12177554,
        -0.02073986,  0.07935159,  0.03321312, -0.07734484, -0.03768014,
         0.04751735],
       [-0.40191716, -0.48235381, -0.12751949, -0.15255742,  0.3289056 ,
        -0.08862975, -0.28894812,  0.18329711,  0.09711557,  0.18461988,
        -0.23438819,  0.03803858,  0.13419605, -0.51193308,  0.21182134,
         0.27017141],
       [-0.81880141, -0.83686935, -0.22066279, -0.26363724,  0.53704118,
        -0.07733828, -0.62136241,  0.28956237,  0.17324121,  0.4910153 ,
        -0.44803652, -0.00327443,  0.23517897, -0.94652132,  0.46132283,
         0.49282547],
       [-1.23568566, -1.19138488, -0.3138061 , -0.37471707,  0.74517675,
        -0.06604681, -0.95377669,  0.39582763,  0.24936686,  0.79741071,
        -0.66168484, -0.04458745,  0.33616189, -1.38110956,  0.71082431,
         0.71547953],
       [-1.65256991, -1.54590042, -0

In [8]:
z = np.maximum(h, 0)
z

array([[0.01496708, 0.        , 0.        , 0.        , 0.12077003,
        0.        , 0.04346617, 0.07703184, 0.02098992, 0.        ,
        0.        , 0.07935159, 0.03321312, 0.        , 0.        ,
        0.04751735],
       [0.        , 0.        , 0.        , 0.        , 0.3289056 ,
        0.        , 0.        , 0.18329711, 0.09711557, 0.18461988,
        0.        , 0.03803858, 0.13419605, 0.        , 0.21182134,
        0.27017141],
       [0.        , 0.        , 0.        , 0.        , 0.53704118,
        0.        , 0.        , 0.28956237, 0.17324121, 0.4910153 ,
        0.        , 0.        , 0.23517897, 0.        , 0.46132283,
        0.49282547],
       [0.        , 0.        , 0.        , 0.        , 0.74517675,
        0.        , 0.        , 0.39582763, 0.24936686, 0.79741071,
        0.        , 0.        , 0.33616189, 0.        , 0.71082431,
        0.71547953],
       [0.        , 0.        , 0.        , 0.        , 0.95331233,
        0.        , 0.        , 

In [9]:
pred_y = z @ W2
pred_y

array([[0.03307772],
       [0.09318015],
       [0.15393643],
       [0.2165908 ],
       [0.27924516]])

In [11]:
Loss = np.mean((y - pred_y.ravel())**2)
Loss

9.85413798437367

### 사례 2
- 입력층 : 뉴런 4개
- 출력층 : 뉴런 1개
- 출력층 활성화함수 : sigmoid
- 중간층 1개 : 뉴런 256개
- 중간층 활성화함수 : ReLU
- Loss : Binary CrossEntropy

In [12]:
X = np.arange(20).reshape(5,4)
y = np.array([1,0,0,1,0])

In [13]:
W1 = np.random.normal(0,0.1,size=[4,256])

In [14]:
W2 = np.random.normal(0,0.1,size=[256,1])

In [16]:
z = np.maximum(X @ W1, 0)
z.shape

(5, 256)

In [17]:
def sigmoid(t):
    return 1/(1+np.exp(-t))

In [18]:
pred_y = np.vectorize(sigmoid)(z @ W2)
pred_y

array([[0.51478113],
       [0.55847061],
       [0.5709369 ],
       [0.59112685],
       [0.61576702]])

In [22]:
Loss = -np.mean(y*np.log(pred_y.ravel()) + (1-y)*np.log(1-pred_y.ravel()))
Loss

0.7619812577959468

### 사례 3
- 입력층 : 뉴런 4개
- 출력층 : 뉴런 3개
- 출력층 활성화함수 : softmax
- 중간층 1개 : 뉴런 256개
- 중간층 활성화함수 : ReLU
- Loss : Categorical CrossEntropy

In [27]:
X = np.arange(20).reshape(5,4)
y = np.array([1,0,2,1,2])

In [28]:
W1 = np.random.normal(0,0.1,size=[4,256])

In [29]:
W2 = np.random.normal(0,0.1,size=[256,3])

In [30]:
z = np.maximum(X @ W1, 0)
z.shape

(5, 256)

In [35]:
def softmax(z):
    t = np.sum(np.exp(z), axis=1)
    return np.exp(z)/t.reshape(-1,1)

In [40]:
pred_y = softmax(z @ W2)
pred_y

array([[2.65199167e-01, 2.19263324e-01, 5.15537509e-01],
       [8.06664148e-02, 5.61050739e-02, 8.63228511e-01],
       [1.70035387e-02, 9.61559184e-03, 9.73380869e-01],
       [3.21552063e-03, 1.51861795e-03, 9.95265861e-01],
       [5.91867510e-04, 2.34255961e-04, 9.99173877e-01]])

In [44]:
onehot_y = np.eye(3)[y]
onehot_y

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
Loss = -np.mean(np.sum(onehot_y * np.log(pred_y), axis=1))
Loss

2.110535149650337

### 사례 4
- 입력층 : 뉴런 4개
- 출력층 : 뉴런 3개
- 출력층 활성화함수 : softmax
- 중간층1 : 뉴런 128개
- 중간층2 : 뉴런 64개
- 중간층 활성화함수 : ReLU
- Loss : Categorical CrossEntropy

In [47]:
X = np.arange(20).reshape(5,4)
y = np.array([1,0,2,1,2])

In [48]:
W1 = np.random.normal(0,0.1,size=[4,128])

In [49]:
W2 = np.random.normal(0,0.1,size=[128,64])

In [50]:
W3 = np.random.normal(0,0.1,size=[64,3])

In [52]:
z1 = np.maximum(X @ W1, 0)
z1.shape

(5, 128)

In [53]:
z2 = np.maximum(z1 @ W2, 0)
z2.shape

(5, 64)

In [54]:
def softmax(z):
    t = np.sum(np.exp(z), axis=1)
    return np.exp(z)/t.reshape(-1,1)

In [55]:
pred_y = softmax(z2 @ W3)
pred_y

array([[0.31357041, 0.35122194, 0.33520766],
       [0.30834938, 0.33747524, 0.35417538],
       [0.30202891, 0.32714673, 0.37082436],
       [0.29190953, 0.31962893, 0.38846155],
       [0.28024489, 0.31044291, 0.40931219]])

In [56]:
onehot_y = np.eye(3)[y]
onehot_y

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
Loss = -np.mean(np.sum(onehot_y * np.log(pred_y), axis=1))
Loss

1.0497514355404436